### ISSUE TITLE
Listen1 v3 进度

### ISSUE THREAD

**Issue by mikelxk** [listen1/listen1_chrome_extension#766]
### 这个issue记录了v3的工作进程
https://github.com/listen1/listen1_chrome_extension/milestone/9
## Refactor 重构

- [x] Use vue3
- [x] Use vite as dev tool #640 #653
- [x] Use indexDB as storage #675 
- [x] Redefine provider interface for extendibility
- [x] Rewrite audio #720
- [x] Use tailwindcss #734 

## Feature 新增功能
- [x] Show comment #738
- [x] Configurable lyric #701 
- [x] Local music cover img #712
- [ ]  Layout improvement #755 #735
## Missing Feature 缺少功能
- [ ] Keyboard shortcut
- [ ] Background playmode
- [ ] Windows thumbnail button
- [ ] Connect to Last.fm
If you want to use v3. You can switch to branch `next` and run `yarn run build`

**Comment by Remonli** [comment]
可以先发一下测试版本呀。

**Comment by mikelxk** [comment]
> 可以先发一下测试版本呀。

发了一个自己构建的版本在上边

**Comment by mikelxk** [comment]
@listen1 Is it a good time to publish a beta release?

**Comment by listen1** [comment]
Beta release will be published when localstorage->indexdb migration test is confirmed, so now it's still on progress.

**Comment by inaryart** [comment]
仍没有计划支持下载吗？ https://github.com/listen1/listen1_chrome_extension/issues/32

**Comment by mikelxk** [comment]
@listen1 When I was trying to make background music available in MV3. I found it nearly impossible to implement the function like mv2 right now. https://stackoverflow.com/questions/73866325/chrome-extension-playing-music-in-the-background
Maybe we need to postpone it until chrome has support on offscreen documents?

**Comment by mikelxk** [comment]
chrome has supported offscreen documents in 108.
https://developer.chrome.com/docs/extensions/reference/offscreen/
https://stackoverflow.com/questions/67437180/play-audio-from-background-script-in-chrome-extention-manifest-v3

**Comment by NothingButKevin** [comment]
Manifest version 2 is completely deprecated in the latest version of Chromium. The update to Manifest v3 is necessary now.
